name: PHP CI

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, gd, zip, pdo_mysql, sockets, intl, bcmath, gmp 
        coverage: xdebug

    - name: Update and Install additional packages
      run: |
        sudo apt-get update
        sudo apt-get install -y libzip-dev libgd-dev libfreetype6-dev libjpeg-dev libpng-dev imagemagick libmagickwand-dev libmemcached-dev libgeos-dev libgmp-dev default-mysql-client libicu-dev

    - name: Configure Composer Auth for Github
      run: composer config --global github-oauth.github.com ${{ secrets._GITHUB_AUTH_TOKEN }}

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run Lint
      run: composer lint

    # - name: Run Tests -- Will add tests back after phppest issue https://github.com/pestphp/pest/issues/920 is fixed
    #   run: composer test:unit
