name: Create Release
on:
  push:
    tags:
      - 'v*'

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Publish GitHub Release
          uses: softprops/action-gh-release@v2
          with:
            tag_name: ${{ github.ref_name }}
            name: ${{ github.ref_name }}
            generate_release_notes: true 
            draft: false
            prerelease: false
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}