natural_earth_update_2.0.0.zip:
	mkdir -p natural_earth_update_2.0.0
	mkdir -p natural_earth_update_2.0.0/10m_cultural
	mkdir -p natural_earth_update_2.0.0/10m_physical
	mkdir -p natural_earth_update_2.0.0/50m_cultural
	mkdir -p natural_earth_update_2.0.0/50m_physical
	mkdir -p natural_earth_update_2.0.0/110m_cultural
	mkdir -p natural_earth_update_2.0.0/110m_physical
	rm -rf natural_earth_update_2.0.0
	rm -rf natural_earth_update_2.0.0/10m_cultural
	rm -rf natural_earth_update_2.0.0/10m_physical
	rm -rf natural_earth_update_2.0.0/50m_cultural
	rm -rf natural_earth_update_2.0.0/50m_physical
	rm -rf natural_earth_update_2.0.0/110m_cultural
	rm -rf natural_earth_update_2.0.0/110m_physical
	
	# TODO: Only the actual files that changed
	# NOT everything, as is shown below.
	
	cp ../10m_cultural/* natural_earth_update_2.0.0/10m_cultural
	cp ../10m_physical/* natural_earth_update_2.0.0/10m_physical
	cp ../50m_cultural/* natural_earth_update_2.0.0/50m_cultural
	cp ../50m_physical/* natural_earth_update_2.0.0/50m_physical
	cp ../110m_cultural/* natural_earth_update_2.0.0/110m_cultural
	cp ../110m_physical/* natural_earth_update_2.0.0/110m_physical
	
