# ---------------------------------------------------------------------------
# a1_build_ne_admin_0_tables.py
# Created on: Sun Nov 04 2012 03:05:29 AM
#   (generated by ArcGIS/ModelBuilder)
# ---------------------------------------------------------------------------

# Import system modules
import sys, string, os, arcgisscripting

# Create the Geoprocessor object
gp = arcgisscripting.create()

# Load required toolboxes...
gp.AddToolbox("C:/Program Files/ArcGIS/ArcToolbox/Toolboxes/Data Management Tools.tbx")
gp.AddToolbox("C:/Program Files/ArcGIS/ArcToolbox/Toolboxes/Analysis Tools.tbx")


# Local variables...
ne_admin_0_details_level_4_subunits_dbf = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\ne_admin_0_details_level_4_subunits.dbf"
ne_admin_0_details_level_3_map_units_dbf = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\ne_admin_0_details_level_3_map_units.dbf"
ne_admin_0_details_level_2_countries_dbf = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\ne_admin_0_details_level_2_countries.dbf"
ne_admin_0_details_level_1_sov_dbf = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\ne_admin_0_details_level_1_sov.dbf"
Sheet1_ = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\ne_admin_0_details.xls\\Sheet1$"
ne_admin_0_details_level_5_disputed_dbf = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\ne_admin_0_details_level_5_disputed.dbf"
ne_admin_0_details_level_2_countries_dbf__2_ = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\ne_admin_0_details_level_2_countries.dbf"
ne_admin_0_details_level_4_subunits_dbf__2_ = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\ne_admin_0_details_level_4_subunits.dbf"
ne_admin_0_details_level_5_disputed_dbf__2_ = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\ne_admin_0_details_level_5_disputed.dbf"
ne_admin_0_details_level_3_map_units_dbf__2_ = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\ne_admin_0_details_level_3_map_units.dbf"
ne_admin_0_details_level_2_countries_dbf__6_ = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\ne_admin_0_details_level_1_sov.dbf"

# Process: Table Select (3)...
gp.TableSelect_analysis(Sheet1_, ne_admin_0_details_level_2_countries_dbf, "`level` <= 2")

# Process: Delete Field...
gp.DeleteField_management(ne_admin_0_details_level_2_countries_dbf, "F51;F52;F53;F54;F55;F56;F57;F58;F59;F60;F61;F62;F63;F64;F65;F66;F67;F68;F69;F70;F71;F72;F73;F74;F75;F76;F77;F78;F79;F80;F81;F82;F83;F84;F85;F86;F87;F88;F89;F90;F91;F92;F93;F94;F95;F96;F97;F98;F99;F100;F101;F102;F103;F104;F105;F106;F107;F108;F109;F110;F111;F112;F113;F114;F115;F116;F117;F118;F119;F120;F121;F122;F123;F124;F125;F126;F127")

# Process: Table Select...
gp.TableSelect_analysis(Sheet1_, ne_admin_0_details_level_4_subunits_dbf, "`level` <= 4")

# Process: Delete Field (2)...
gp.DeleteField_management(ne_admin_0_details_level_4_subunits_dbf, "F51;F52;F53;F54;F55;F56;F57;F58;F59;F60;F61;F62;F63;F64;F65;F66;F67;F68;F69;F70;F71;F72;F73;F74;F75;F76;F77;F78;F79;F80;F81;F82;F83;F84;F85;F86;F87;F88;F89;F90;F91;F92;F93;F94;F95;F96;F97;F98;F99;F100;F101;F102;F103;F104;F105;F106;F107;F108;F109;F110;F111;F112;F113;F114;F115;F116;F117;F118;F119;F120;F121;F122;F123;F124;F125;F126;F127")

# Process: Table Select (5)...
gp.TableSelect_analysis(Sheet1_, ne_admin_0_details_level_5_disputed_dbf, "`level` <= 5")

# Process: Delete Field (3)...
gp.DeleteField_management(ne_admin_0_details_level_5_disputed_dbf, "F51;F52;F53;F54;F55;F56;F57;F58;F59;F60;F61;F62;F63;F64;F65;F66;F67;F68;F69;F70;F71;F72;F73;F74;F75;F76;F77;F78;F79;F80;F81;F82;F83;F84;F85;F86;F87;F88;F89;F90;F91;F92;F93;F94;F95;F96;F97;F98;F99;F100;F101;F102;F103;F104;F105;F106;F107;F108;F109;F110;F111;F112;F113;F114;F115;F116;F117;F118;F119;F120;F121;F122;F123;F124;F125;F126;F127")

# Process: Table Select (2)...
gp.TableSelect_analysis(Sheet1_, ne_admin_0_details_level_3_map_units_dbf, "`level` <= 3")

# Process: Delete Field (4)...
gp.DeleteField_management(ne_admin_0_details_level_3_map_units_dbf, "F51;F52;F53;F54;F55;F56;F57;F58;F59;F60;F61;F62;F63;F64;F65;F66;F67;F68;F69;F70;F71;F72;F73;F74;F75;F76;F77;F78;F79;F80;F81;F82;F83;F84;F85;F86;F87;F88;F89;F90;F91;F92;F93;F94;F95;F96;F97;F98;F99;F100;F101;F102;F103;F104;F105;F106;F107;F108;F109;F110;F111;F112;F113;F114;F115;F116;F117;F118;F119;F120;F121;F122;F123;F124;F125;F126;F127")

# Process: Table Select (4)...
gp.TableSelect_analysis(Sheet1_, ne_admin_0_details_level_1_sov_dbf, "`level` <= 2 And ( `type` = 'Indeterminate' Or `type` = 'Sovereign country' Or `type` = 'Sovereignty' Or `type` = 'Trap Street' )")

# Process: Delete Field (5)...
gp.DeleteField_management(ne_admin_0_details_level_1_sov_dbf, "F51;F52;F53;F54;F55;F56;F57;F58;F59;F60;F61;F62;F63;F64;F65;F66;F67;F68;F69;F70;F71;F72;F73;F74;F75;F76;F77;F78;F79;F80;F81;F82;F83;F84;F85;F86;F87;F88;F89;F90;F91;F92;F93;F94;F95;F96;F97;F98;F99;F100;F101;F102;F103;F104;F105;F106;F107;F108;F109;F110;F111;F112;F113;F114;F115;F116;F117;F118;F119;F120;F121;F122;F123;F124;F125;F126;F127")

