# ---------------------------------------------------------------------------
# build_a2_ne_10m_admin_0_disputed.py
# Created on: Sat Aug 19 2017 11:43:16 PM
#   (generated by ArcGIS/ModelBuilder)
# ---------------------------------------------------------------------------

# Import system modules
import sys, string, os, arcgisscripting

# Create the Geoprocessor object
gp = arcgisscripting.create()

# Set the necessary product code
gp.SetProduct("ArcInfo")

# Load required toolboxes...
gp.AddToolbox("C:/Program Files/ArcGIS/ArcToolbox/Toolboxes/Data Management Tools.tbx")
gp.AddToolbox("C:/Program Files/ArcGIS/ArcToolbox/Toolboxes/Analysis Tools.tbx")


# Local variables...
ne_10m_admin_0_disputed_areas_shp__3_ = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\10m_cultural\\ne_10m_admin_0_disputed_areas.shp"
ne_10m_admin_0_map_subunits_test_shp__3_ = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\10m_cultural\\ne_10m_admin_0_disputed_areas_tmp.shp"
ne_10m_admin_0_map_subunits_test_shp__4_ = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\10m_cultural\\ne_10m_admin_0_disputed_areas_tmp.shp"
ne_10m_admin_0_map_subunits_test_shp__5_ = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\10m_cultural\\ne_10m_admin_0_disputed_areas_tmp.shp"
ne_10m_admin_0_map_subunits_test_shp__8_ = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\10m_cultural\\ne_10m_admin_0_disputed_areas_tmp.shp"
ne_10m_admin_0_disputed_areas_tmp_shp__2_ = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\10m_cultural\\ne_10m_admin_0_disputed_areas_tmp.shp"
ne_10m_admin_0_disputed_areas_scale_rank_minor_islands_shp = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\10m_cultural\\ne_10m_admin_0_disputed_areas_scale_rank_minor_islands.shp"
ne_admin_0_details_level_5_disputed_dbf = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\housekeeping\\ne_admin_0_details_level_5_disputed.dbf"
ne_10m_admin_0_disputed_areas_shp = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\10m_cultural\\ne_10m_admin_0_disputed_areas.shp"
ne_10m_admin_0_disputed_areas_tmp_shp = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\10m_cultural\\ne_10m_admin_0_disputed_areas_tmp.shp"
ne_10m_admin_0_scale_rank_minor_islands_shp = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\10m_cultural\\ne_10m_admin_0_scale_rank_minor_islands.shp"
Output_Feature_Class__2_ = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\10m_cultural\\ne_10m_admin_0_disputed_areas.shp"

# Process: Select...
gp.Select_analysis(ne_10m_admin_0_scale_rank_minor_islands_shp, ne_10m_admin_0_disputed_areas_scale_rank_minor_islands_shp, "\"featurecla\" = 'Admin-0 breakaway and disputed' Or \"featurecla\" = 'Admin-0 claim area' Or \"featurecla\" = 'Admin-0 indeterminant' Or \"featurecla\" = 'Admin-0 overlay' Or \"featurecla\" = 'Admin-0 lease'")

# Process: Dissolve (2)...
gp.Dissolve_management(ne_10m_admin_0_disputed_areas_scale_rank_minor_islands_shp, ne_10m_admin_0_disputed_areas_tmp_shp, "sr_brk_a3", "scalerank MIN;featurecla FIRST", "MULTI_PART", "DISSOLVE_LINES")

# Process: Add Field (2)...
gp.AddField_management(ne_10m_admin_0_disputed_areas_tmp_shp, "scalerank", "SHORT", "", "", "", "", "NON_NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field...
gp.CalculateField_management(ne_10m_admin_0_map_subunits_test_shp__4_, "scalerank", "[MIN_scaler]", "VB", "")

# Process: Add Field...
gp.AddField_management(ne_10m_admin_0_map_subunits_test_shp__5_, "featurecla", "TEXT", "", "", "30", "", "NON_NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (2)...
gp.CalculateField_management(ne_10m_admin_0_map_subunits_test_shp__3_, "featurecla", "[FIRST_feat]", "VB", "")

# Process: Delete Field...
gp.DeleteField_management(ne_10m_admin_0_map_subunits_test_shp__8_, "MIN_scaler;FIRST_feat")

# Process: Select (2)...
gp.Select_analysis(ne_10m_admin_0_disputed_areas_tmp_shp__2_, ne_10m_admin_0_disputed_areas_shp, "\"scalerank\" >= 0")

# Process: Repair Geometry (2)...
gp.RepairGeometry_management(ne_10m_admin_0_disputed_areas_shp, "DELETE_NULL")

# Process: Join Field...
gp.JoinField_management(Output_Feature_Class__2_, "sr_brk_a3", ne_admin_0_details_level_5_disputed_dbf, "BRK_A3", "")

