# ---------------------------------------------------------------------------
# build_c3_ne_110m_admin_0_sov.py
# Created on: Sat Aug 19 2017 11:45:28 PM
#   (generated by ArcGIS/ModelBuilder)
# ---------------------------------------------------------------------------

# Import system modules
import sys, string, os, arcgisscripting

# Create the Geoprocessor object
gp = arcgisscripting.create()

# Set the necessary product code
gp.SetProduct("ArcInfo")

# Load required toolboxes...
gp.AddToolbox("C:/Program Files/ArcGIS/ArcToolbox/Toolboxes/Data Management Tools.tbx")


# Local variables...
ne_110m_admin_0_sovereignty_shp = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\110m_cultural\\ne_110m_admin_0_sovereignty.shp"
ne_10m_admin_0_countries_shp__2_ = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\110m_cultural\\ne_110m_admin_0_sovereignty.shp"
ne_10m_admin_0_map_subunits_test_shp__3_ = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\110m_cultural\\ne_110m_admin_0_sovereignty.shp"
ne_10m_admin_0_map_subunits_test_shp__4_ = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\110m_cultural\\ne_110m_admin_0_sovereignty.shp"
ne_10m_admin_0_map_subunits_test_shp__5_ = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\110m_cultural\\ne_110m_admin_0_sovereignty.shp"
ne_10m_admin_0_sovereignty_shp__4_ = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\110m_cultural\\ne_110m_admin_0_sovereignty.shp"
ne_10m_admin_0_map_subunits_test_shp__7_ = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\110m_cultural\\ne_110m_admin_0_sovereignty.shp"
ne_admin_0_details_level_1_sov_dbf = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\housekeeping\\ne_admin_0_details_level_1_sov.dbf"
ne_110m_admin_0_scale_rank_shp = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\110m_cultural\\ne_110m_admin_0_scale_rank.shp"
Output_Feature_Class = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\110m_cultural\\ne_110m_admin_0_sovereignty.shp"
ne_110m_admin_0_sovereignty_shp__2_ = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\110m_cultural\\ne_110m_admin_0_sovereignty.shp"

# Process: Dissolve...
gp.Dissolve_management(ne_110m_admin_0_scale_rank_shp, ne_110m_admin_0_sovereignty_shp, "sr_sov_a3", "scalerank MIN", "MULTI_PART", "DISSOLVE_LINES")

# Process: Add Field (2)...
gp.AddField_management(ne_110m_admin_0_sovereignty_shp, "scalerank", "SHORT", "", "", "", "", "NON_NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field...
gp.CalculateField_management(ne_10m_admin_0_map_subunits_test_shp__4_, "scalerank", "[MIN_scaler]", "VB", "")

# Process: Add Field...
gp.AddField_management(ne_10m_admin_0_map_subunits_test_shp__5_, "featurecla", "TEXT", "", "", "30", "", "NON_NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (2)...
gp.CalculateField_management(ne_10m_admin_0_map_subunits_test_shp__3_, "featurecla", "\"Admin-0 sovereignty\"", "VB", "")

# Process: Delete Field...
gp.DeleteField_management(ne_10m_admin_0_sovereignty_shp__4_, "MIN_scaler")

# Process: Repair Geometry...
gp.RepairGeometry_management(ne_10m_admin_0_map_subunits_test_shp__7_, "DELETE_NULL")

# Process: Join Field...
gp.JoinField_management(Output_Feature_Class, "sr_sov_a3", ne_admin_0_details_level_1_sov_dbf, "sov_a3", "")

# Process: Delete Field (2)...
gp.DeleteField_management(ne_10m_admin_0_countries_shp__2_, "sr_sov_a3")

