# ---------------------------------------------------------------------------
# build_c4_ne_110m_admin_1.py
# Created on: Sat Aug 19 2017 11:46:03 PM
#   (generated by ArcGIS/ModelBuilder)
# ---------------------------------------------------------------------------

# Import system modules
import sys, string, os, arcgisscripting

# Create the Geoprocessor object
gp = arcgisscripting.create()

# Set the necessary product code
gp.SetProduct("ArcInfo")

# Load required toolboxes...
gp.AddToolbox("C:/Program Files/ArcGIS/ArcToolbox/Toolboxes/Data Management Tools.tbx")
gp.AddToolbox("C:/Program Files/ArcGIS/ArcToolbox/Toolboxes/Analysis Tools.tbx")


# Local variables...
ne_110m_admin_1_states_provinces_lakes_shp = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\110m_cultural\\ne_110m_admin_1_states_provinces_lakes.shp"
ne_110m_lakes_tmp_admin_1_erase_shp = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\110m_physical\\ne_110m_lakes_tmp_admin_1_erase.shp"
ne_110m_lakes_shp = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\110m_physical\\ne_110m_lakes.shp"
ne_10m_admin_1_states_provinces_geodb_tmp__2_ = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\110m_cultural\\ne_110m_admin_1_states_provinces.shp"
ne_110m_admin_1_states_provinces_scale_rank_shp = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\110m_cultural\\ne_110m_admin_1_states_provinces_scale_rank.shp"
ne_10m_admin_1_label_points_details_shp = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\10m_cultural\\ne_10m_admin_1_label_points_details.shp"
ne_110m_admin_1_states_provinces_shp = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\110m_cultural\\ne_110m_admin_1_states_provinces.shp"
ne_50m_admin_1_states_provinces_shp__2_ = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\110m_cultural\\ne_110m_admin_1_states_provinces.shp"
ne_50m_admin_1_states_provinces_shp__4_ = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\110m_cultural\\ne_110m_admin_1_states_provinces.shp"

# Process: Select (2)...
gp.Select_analysis(ne_110m_admin_1_states_provinces_scale_rank_shp, ne_110m_admin_1_states_provinces_shp, "\"scalerank\" >= 0")

# Process: Delete Field (2)...
gp.DeleteField_management(ne_110m_admin_1_states_provinces_shp, "featurecla;scalerank;adm1_cod_1;MIN_scaler")

# Process: Join Field...
gp.JoinField_management(ne_50m_admin_1_states_provinces_shp__4_, "adm1_code", ne_10m_admin_1_label_points_details_shp, "adm1_code", "")

# Process: Delete Field...
gp.DeleteField_management(ne_10m_admin_1_states_provinces_geodb_tmp__2_, "adm1_cod_1;MIN_scaler")

# Process: Select (3)...
gp.Select_analysis(ne_110m_lakes_shp, ne_110m_lakes_tmp_admin_1_erase_shp, "\"admin\" = 'admin-0' Or \"admin\" = 'admin-0 more'")

# Process: Erase...
gp.Erase_analysis(ne_50m_admin_1_states_provinces_shp__2_, ne_110m_lakes_tmp_admin_1_erase_shp, ne_110m_admin_1_states_provinces_lakes_shp, "")

