# ---------------------------------------------------------------------------
# build_a7_ne_10m_admin_1_all.py
# Created on: Sat Aug 19 2017 11:44:29 PM
#   (generated by ArcGIS/ModelBuilder)
# ---------------------------------------------------------------------------

# Import system modules
import sys, string, os, arcgisscripting

# Create the Geoprocessor object
gp = arcgisscripting.create()

# Set the necessary product code
gp.SetProduct("ArcInfo")

# Load required toolboxes...
gp.AddToolbox("C:/Program Files/ArcGIS/ArcToolbox/Toolboxes/Data Management Tools.tbx")
gp.AddToolbox("C:/Program Files/ArcGIS/ArcToolbox/Toolboxes/Analysis Tools.tbx")


# Local variables...
ne_10m_admin_0_boundary_lines_land_shp = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\10m_cultural\\ne_10m_admin_0_boundary_lines_land.shp"
ne_10m_minor_islands_coastline_shp = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\10m_physical\\ne_10m_minor_islands_coastline.shp"
ne_10m_coastline_shp = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\10m_physical\\ne_10m_coastline.shp"
ne_10m_admin_1_states_provinces_scale_rank_minor_islands_tmp_shp = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\10m_cultural\\ne_10m_admin_1_states_provinces_scale_rank_minor_islands_tmp.shp"
ne_10m_admin_1_states_provinces_scale_rank_minor_islands_shp = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\10m_cultural\\ne_10m_admin_1_states_provinces_scale_rank_minor_islands.shp"
ne_10m_admin_1_label_points_shp = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\10m_cultural\\ne_10m_admin_1_label_points.shp"
ne_10m_admin_1_states_provinces_lines_shp = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\10m_cultural\\ne_10m_admin_1_states_provinces_lines.shp"
ne_10m_admin_0_boundary_lines_map_units_shp = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\10m_cultural\\ne_10m_admin_0_boundary_lines_map_units.shp"
ne_10m_admin_1_states_provinces_scale_rank_shp = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\10m_cultural\\ne_10m_admin_1_states_provinces_scale_rank.shp"
ne_10m_admin_1_seams_shp = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\10m_cultural\\ne_10m_admin_1_seams.shp"
ne_10m_admin_1_states_provinces_shp = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\10m_cultural\\ne_10m_admin_1_states_provinces.shp"
ne_10m_admin_1_label_points_details_shp = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\10m_cultural\\ne_10m_admin_1_label_points_details.shp"
ne_10m_admin_1_states_provinces_geodb_tmp__2_ = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\10m_cultural\\ne_10m_admin_1_states_provinces.shp"
ne_10m_admin_1_states_provinces_lakes_shp = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\10m_cultural\\ne_10m_admin_1_states_provinces_lakes.shp"
ne_10m_lakes_shp = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\10m_physical\\ne_10m_lakes.shp"
ne_10m_lakes_tmp_admin_1_erase_shp = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\10m_physical\\ne_10m_lakes_tmp_admin_1_erase.shp"
ne_10m_admin_1_states_provinces_shp__2_ = "C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\10m_cultural\\ne_10m_admin_1_states_provinces.shp"

# Process: Feature To Polygon...
gp.FeatureToPolygon_management("C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\10m_physical\\ne_10m_coastline.shp;C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\10m_physical\\ne_10m_minor_islands_coastline.shp;C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\10m_cultural\\ne_10m_admin_0_boundary_lines_land.shp;C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\10m_cultural\\ne_10m_admin_1_states_provinces_lines.shp;C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\10m_cultural\\ne_10m_admin_0_boundary_lines_map_units.shp;C:\\ProjectFiles\\NaturalEarth\\nev_version_4d0d0\\10m_cultural\\ne_10m_admin_1_seams.shp", ne_10m_admin_1_states_provinces_scale_rank_minor_islands_tmp_shp, "", "ATTRIBUTES", ne_10m_admin_1_label_points_shp)

# Process: Select...
gp.Select_analysis(ne_10m_admin_1_states_provinces_scale_rank_minor_islands_tmp_shp, ne_10m_admin_1_states_provinces_scale_rank_minor_islands_shp, "\"sr_adm0_a3\" <> ' '")

# Process: Select (2)...
gp.Select_analysis(ne_10m_admin_1_states_provinces_scale_rank_minor_islands_shp, ne_10m_admin_1_states_provinces_scale_rank_shp, "\"adm0_sr\" <= 6")

# Process: Dissolve...
gp.Dissolve_management(ne_10m_admin_1_states_provinces_scale_rank_shp, ne_10m_admin_1_states_provinces_shp, "adm1_code", "", "MULTI_PART", "DISSOLVE_LINES")

# Process: Join Field...
gp.JoinField_management(ne_10m_admin_1_states_provinces_shp, "adm1_code", ne_10m_admin_1_label_points_details_shp, "adm1_code", "")

# Process: Delete Field...
gp.DeleteField_management(ne_10m_admin_1_states_provinces_geodb_tmp__2_, "adm1_cod_1;MIN_scaler")

# Process: Select (3)...
gp.Select_analysis(ne_10m_lakes_shp, ne_10m_lakes_tmp_admin_1_erase_shp, "\"admin\" = 'admin-0' Or \"admin\" = 'admin-0 more'")

# Process: Erase...
gp.Erase_analysis(ne_10m_admin_1_states_provinces_shp__2_, ne_10m_lakes_tmp_admin_1_erase_shp, ne_10m_admin_1_states_provinces_lakes_shp, "")

