zips: land_10m.zip land_50m.zip land_110m.zip roads_10m.zip roads_north_america_10m.zip urban_areas_10m.zip \
	  urban_areas_50m.zip urban_areas_landscan_10m.zip admin_0_boundary_breakaway_disputed_areas_10m.zip \
	  admin_0_boundary_breakaway_disputed_areas_50m.zip admin_0_boundary_lines_land_10m.zip \
	  admin_0_boundary_lines_land_50m.zip admin_0_boundary_lines_land_110m.zip admin_0_boundary_lines_map_units_10m.zip \
	  admin_0_boundary_lines_maritime_indicator_10m.zip admin_0_boundary_lines_maritime_indicator_50m.zip \
	  admin_0_boundary_map_units_50m.zip admin_0_breakaway_disputed_areas_10m.zip \
	  admin_0_breakaway_disputed_areas_50m.zip admin_0_breakaway_disputed_areas_scale_ranks_10m.zip \
	  admin_0_countries_10m.zip admin_0_countries_50m.zip admin_0_countries_110m.zip admin_0_map_subunits_10m.zip \
	  admin_0_map_subunits_50m.zip admin_0_map_units_10m.zip admin_0_map_units_50m.zip admin_0_map_units_110m.zip \
	  admin_0_pacific_groupings_10m.zip admin_0_pacific_groupings_50m.zip admin_0_pacific_groupings_110m.zip \
	  admin_0_scale_ranks_50m.zip admin_0_scale_ranks_110m.zip \
	  admin_0_scale_ranks_with_minor_islands_10m.zip admin_0_sovereignty_10m.zip admin_0_sovereignty_50m.zip \
	  admin_0_sovereignty_110m.zip admin_0_tiny_countries_50m.zip admin_0_tiny_countries_110m.zip \
	  admin_1_states_provinces_lakes_shp_10m.zip admin_1_states_provinces_lines_shp_10m.zip \
	  admin_1_states_provinces_lines_shp_50m.zip admin_1_states_provinces_lines_shp_110m.zip \
	  admin_1_states_provinces_shp_10m.zip admin_1_states_provinces_shp_50m.zip admin_1_states_provinces_shp_110m.zip \
	  antarctic_ice_shelves_lines_10m.zip antarctic_ice_shelves_lines_50m.zip antarctic_ice_shelves_polys_10m.zip \
	  antarctic_ice_shelves_polys_50m.zip bathymetry_A_10000_10m.zip bathymetry_B_9000_10m.zip bathymetry_C_8000_10m.zip \
	  bathymetry_D_7000_10m.zip bathymetry_E_6000_10m.zip bathymetry_F_5000_10m.zip bathymetry_G_4000_10m.zip \
	  bathymetry_H_3000_10m.zip bathymetry_I_2000_10m.zip bathymetry_J_1000_10m.zip bathymetry_K_200_10m.zip \
	  bathymetry_L_0_10m.zip coastline_10m.zip coastline_50m.zip coastline_110m.zip geographic_lines_10m.zip \
	  geographic_lines_50m.zip geographic_lines_110m.zip geography_marine_polys_10m.zip geography_marine_polys_50m.zip \
	  geography_marine_polys_110m.zip geography_regions_elevation_points_10m.zip \
	  geography_regions_elevation_points_50m.zip geography_regions_elevation_points_110m.zip \
	  geography_regions_points_10m.zip geography_regions_points_50m.zip geography_regions_points_110m.zip \
	  geography_regions_polys_10m.zip geography_regions_polys_50m.zip geography_regions_polys_110m.zip \
	  glaciated_areas_10m.zip glaciated_areas_50m.zip glaciated_areas_110m.zip graticules_1_10m.zip graticules_5_10m.zip \
	  graticules_10_10m.zip graticules_15_10m.zip graticules_20_10m.zip graticules_30_10m.zip graticules_1_50m.zip \
	  graticules_5_50m.zip graticules_10_50m.zip graticules_15_50m.zip graticules_20_50m.zip graticules_30_50m.zip \
	  graticules_1_110m.zip graticules_5_110m.zip graticules_10_110m.zip graticules_15_110m.zip graticules_20_110m.zip \
	  graticules_30_110m.zip wgs84_bounding_box_10m.zip wgs84_bounding_box_50m.zip wgs84_bounding_box_110m.zip \
	  lakes_10m.zip lakes_50m.zip lakes_110m.zip lakes_europe_10m.zip lakes_historic_10m.zip lakes_historic_50m.zip \
	  lakes_north_america_10m.zip lakes_pluvial_10m.zip minor_islands_10m.zip minor_islands_coastline_10m.zip \
	  ocean_10m.zip ocean_50m.zip ocean_110m.zip us_parks_area_10m.zip us_parks_line_10m.zip us_parks_point_10m.zip \
	  physical_geographic_lines_110m.zip playas_10m.zip playas_50m.zip populated_places_10m.zip populated_places_50m.zip \
	  populated_places_110m.zip populated_places_simple_10m.zip populated_places_simple_50m.zip \
	  populated_places_simple_110m.zip railroads_10m.zip reefs_10m.zip rivers_europe_10m.zip \
	  rivers_lake_centerlines_10m.zip rivers_lake_centerlines_50m.zip rivers_lake_centerlines_110m.zip \
	  rivers_lake_centerlines_scale_ranks_10m.zip rivers_lake_centerlines_scale_ranks_50m.zip \
	  rivers_north_america_10m.zip \
	  admin_0_antarctic_claims_10m.zip \
	  admin_0_antarctic_claim_limit_lines_10m.zip \
	  parks_and_protected_lands_scale_rank_10m.zip \
	  airports_10m.zip \
	  ports_10m.zip \
	  airports_50m.zip \
	  ports_50m.zip \
	  time_zones_10m.zip \
	  land_scale_ranks_10m.zip \
	  ocean_scale_ranks_10m.zip \
	  admin_0_tiny_countries_scale_rank_50m.zip \
	  admin_1_states_provinces_shp_scale_rank_50m.zip \
	  admin_1_states_provinces_lakes_shp_50m.zip \
	  admin_1_states_provinces_shp_scale_rank_110m.zip \
	  land_ocean_label_points_10m.zip \
	  minor_island_label_points_10m.zip \
	  admin_0_label_points_10m.zip \
	  land_ocean_seams_10m.zip \
	  admin_0_seams_10m.zip \
	  admin_1_seams_10m.zip
	  
	mkdir -p zips
	ln -f land_*m.zip zips/
	ln -f admin_0_boundary_breakaway_disputed_areas_*m.zip zips/
	ln -f admin_0_boundary_lines_land_*m.zip zips/
	ln -f admin_0_boundary_lines_map_units_*m.zip zips/
	ln -f admin_0_boundary_lines_maritime_indicator_*m.zip zips/
	ln -f admin_0_boundary_map_units_*m.zip zips/
	ln -f admin_0_breakaway_disputed_areas_*m.zip zips/
	ln -f admin_0_countries_*m.zip zips/
	ln -f admin_0_map_subunits_*m.zip zips/
	ln -f admin_0_map_units_*m.zip zips/
	ln -f admin_0_pacific_groupings_*m.zip zips/
	ln -f admin_0_scale_ranks_*m.zip zips/
	ln -f admin_0_sovereignty_*m.zip zips/
	ln -f admin_0_tiny_countries_*m.zip zips/
	ln -f admin_1_states_provinces_lakes_shp_*m.zip zips/
	ln -f admin_1_states_provinces_lines_shp_*m.zip zips/
	ln -f admin_1_states_provinces_shp_*m.zip zips/
	ln -f antarctic_ice_shelves_lines_*m.zip zips/
	ln -f antarctic_ice_shelves_polys_*m.zip zips/
	ln -f bathymetry_A_10000_*m.zip zips/
	ln -f bathymetry_B_9000_*m.zip zips/
	ln -f bathymetry_C_8000_*m.zip zips/
	ln -f bathymetry_D_7000_*m.zip zips/
	ln -f bathymetry_E_6000_*m.zip zips/
	ln -f bathymetry_F_5000_*m.zip zips/
	ln -f bathymetry_G_4000_*m.zip zips/
	ln -f bathymetry_H_3000_*m.zip zips/
	ln -f bathymetry_I_2000_*m.zip zips/
	ln -f bathymetry_J_1000_*m.zip zips/
	ln -f bathymetry_K_200_*m.zip zips/
	ln -f bathymetry_L_0_*m.zip zips/
	ln -f coastline_*m.zip zips/
	ln -f geographic_lines_*m.zip zips/
	ln -f geography_marine_polys_*m.zip zips/
	ln -f geography_regions_elevation_points_*m.zip zips/
	ln -f geography_regions_points_*m.zip zips/
	ln -f geography_regions_polys_*m.zip zips/
	ln -f glaciated_areas_*m.zip zips/
	ln -f graticules_1_*m.zip zips/
	ln -f graticules_5_*m.zip zips/
	ln -f graticules_10_*m.zip zips/
	ln -f graticules_15_*m.zip zips/
	ln -f graticules_20_*m.zip zips/
	ln -f graticules_30_*m.zip zips/
	ln -f wgs84_bounding_box_*m.zip zips/
	ln -f lakes_*m.zip zips/
	ln -f minor_islands_*m.zip zips/
	ln -f ocean_*m.zip zips/
	ln -f us_parks_area_*m.zip zips/
	ln -f us_parks_line_*m.zip zips/
	ln -f us_parks_point_*m.zip zips/
	ln -f physical_geographic_lines_*m.zip zips/
	ln -f playas_*m.zip zips/
	ln -f populated_places_*m.zip zips/
	ln -f railroads_*m.zip zips/
	ln -f reefs_*m.zip zips/
	ln -f rivers_europe_*m.zip zips/
	ln -f rivers_lake_centerlines_*m.zip zips/
	ln -f rivers_north_america_*m.zip zips/
	ln -f roads_*m.zip zips/
	ln -f urban_areas_*m.zip zips/
	ln -f admin_0_antarctic_claims_*m.zip zips/
	ln -f admin_0_antarctic_claim_limit_lines_*m.zip zips/
	ln -f parks_and_protected_lands_scale_ranks_*m.zip zips/
	ln -f airports_*m.zip zips/
	ln -f ports_*m.zip zips/
	ln -f time_zones_*m.zip zips/
	ln -f land_scale_ranks_*m.zip zips/
	ln -f ocean_scale_ranks_*m.zip zips/
	ln -f admin_0_tiny_countries_scale_rank_*m.zip zips/
	ln -f admin_1_states_provinces_shp_scale_rank_*m.zip zips/
	ln -f land_ocean_label_points_*m.zip zips/
	ln -f minor_island_label_points_*m.zip zips/
	ln -f admin_0_label_points_*m.zip zips/
	ln -f land_ocean_seams_*m.zip zips/
	ln -f admin_0_seams_*m.zip zips/
	ln -f admin_1_seams_*m.zip zips/



land_10m.zip: ../../10m_physical/ne_10m_land.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_physical/ne_10m_land.shp $@ 1>/dev/null 2>&1

land_50m.zip: ../../50m_physical/ne_50m_land.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../50m_physical/ne_50m_land.shp $@ 1>/dev/null 2>&1

land_110m.zip: ../../110m_physical/ne_110m_land.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../110m_physical/ne_110m_land.shp $@ 1>/dev/null 2>&1

admin_0_boundary_breakaway_disputed_areas_10m.zip: ../../10m_cultural/ne_10m_admin_0_boundary_lines_disputed_areas.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_cultural/ne_10m_admin_0_boundary_lines_disputed_areas.shp $@ 1>/dev/null 2>&1

admin_0_boundary_breakaway_disputed_areas_50m.zip: ../../50m_cultural/ne_50m_admin_0_boundary_lines_disputed_areas.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../50m_cultural/ne_50m_admin_0_boundary_lines_disputed_areas.shp $@ 1>/dev/null 2>&1

admin_0_boundary_lines_land_10m.zip: ../../10m_cultural/ne_10m_admin_0_boundary_lines_land.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_cultural/ne_10m_admin_0_boundary_lines_land.shp $@ 1>/dev/null 2>&1

admin_0_boundary_lines_land_50m.zip: ../../50m_cultural/ne_50m_admin_0_boundary_lines_land.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../50m_cultural/ne_50m_admin_0_boundary_lines_land.shp $@ 1>/dev/null 2>&1

admin_0_boundary_lines_land_110m.zip: ../../110m_cultural/ne_110m_admin_0_boundary_lines_land.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../110m_cultural/ne_110m_admin_0_boundary_lines_land.shp $@ 1>/dev/null 2>&1

admin_0_boundary_lines_map_units_10m.zip: ../../10m_cultural/ne_10m_admin_0_boundary_lines_map_units.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_cultural/ne_10m_admin_0_boundary_lines_map_units.shp $@ 1>/dev/null 2>&1

admin_0_boundary_lines_maritime_indicator_10m.zip: ../../10m_cultural/ne_10m_admin_0_boundary_lines_maritime_indicator.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_cultural/ne_10m_admin_0_boundary_lines_maritime_indicator.shp $@ 1>/dev/null 2>&1

admin_0_boundary_lines_maritime_indicator_50m.zip: ../../50m_cultural/ne_50m_admin_0_boundary_lines_maritime_indicator.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../50m_cultural/ne_50m_admin_0_boundary_lines_maritime_indicator.shp $@ 1>/dev/null 2>&1

admin_0_boundary_map_units_50m.zip: ../../50m_cultural/ne_50m_admin_0_boundary_map_units.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../50m_cultural/ne_50m_admin_0_boundary_map_units.shp $@ 1>/dev/null 2>&1

admin_0_breakaway_disputed_areas_10m.zip: ../../10m_cultural/ne_10m_admin_0_disputed_areas.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_cultural/ne_10m_admin_0_disputed_areas.shp $@ 1>/dev/null 2>&1

admin_0_breakaway_disputed_areas_50m.zip: ../../50m_cultural/ne_50m_admin_0_breakaway_disputed_areas.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../50m_cultural/ne_50m_admin_0_breakaway_disputed_areas.shp $@ 1>/dev/null 2>&1

admin_0_breakaway_disputed_areas_scale_ranks_10m.zip: ../../10m_cultural/ne_10m_admin_0_disputed_areas_scale_rank_minor_islands.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_cultural/ne_10m_admin_0_disputed_areas_scale_rank_minor_islands.shp $@ 1>/dev/null 2>&1

admin_0_countries_10m.zip: ../../10m_cultural/ne_10m_admin_0_countries.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_cultural/ne_10m_admin_0_countries.shp $@ 1>/dev/null 2>&1

admin_0_countries_50m.zip: ../../50m_cultural/ne_50m_admin_0_countries.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../50m_cultural/ne_50m_admin_0_countries.shp $@ 1>/dev/null 2>&1

admin_0_countries_110m.zip: ../../110m_cultural/ne_110m_admin_0_countries.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../110m_cultural/ne_110m_admin_0_countries.shp $@ 1>/dev/null 2>&1

admin_0_map_subunits_10m.zip: ../../10m_cultural/ne_10m_admin_0_map_subunits.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_cultural/ne_10m_admin_0_map_subunits.shp $@ 1>/dev/null 2>&1

admin_0_map_subunits_50m.zip: ../../50m_cultural/ne_50m_admin_0_map_subunits.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../50m_cultural/ne_50m_admin_0_map_subunits.shp $@ 1>/dev/null 2>&1

admin_0_map_units_10m.zip: ../../10m_cultural/ne_10m_admin_0_map_units.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_cultural/ne_10m_admin_0_map_units.shp $@ 1>/dev/null 2>&1

admin_0_map_units_50m.zip: ../../50m_cultural/ne_50m_admin_0_map_units.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../50m_cultural/ne_50m_admin_0_map_units.shp $@ 1>/dev/null 2>&1

admin_0_map_units_110m.zip: ../../110m_cultural/ne_110m_admin_0_map_units.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../110m_cultural/ne_110m_admin_0_map_units.shp $@ 1>/dev/null 2>&1

admin_0_pacific_groupings_10m.zip: ../../10m_cultural/ne_10m_admin_0_pacific_groupings.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_cultural/ne_10m_admin_0_pacific_groupings.shp $@ 1>/dev/null 2>&1

admin_0_pacific_groupings_50m.zip: ../../50m_cultural/ne_50m_admin_0_pacific_groupings.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../50m_cultural/ne_50m_admin_0_pacific_groupings.shp $@ 1>/dev/null 2>&1

admin_0_pacific_groupings_110m.zip: ../../110m_cultural/ne_110m_admin_0_pacific_groupings.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../110m_cultural/ne_110m_admin_0_pacific_groupings.shp $@ 1>/dev/null 2>&1

admin_0_scale_ranks_50m.zip: ../../50m_cultural/ne_50m_admin_0_scale_rank.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../50m_cultural/ne_50m_admin_0_scale_rank.shp $@ 1>/dev/null 2>&1

admin_0_scale_ranks_110m.zip: ../../110m_cultural/ne_110m_admin_0_scale_rank.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../110m_cultural/ne_110m_admin_0_scale_rank.shp $@ 1>/dev/null 2>&1

admin_0_scale_ranks_with_minor_islands_10m.zip: ../../10m_cultural/ne_10m_admin_0_scale_rank_minor_islands.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_cultural/ne_10m_admin_0_scale_rank_minor_islands.shp $@ 1>/dev/null 2>&1

admin_0_sovereignty_10m.zip: ../../10m_cultural/ne_10m_admin_0_sovereignty.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_cultural/ne_10m_admin_0_sovereignty.shp $@ 1>/dev/null 2>&1

admin_0_sovereignty_50m.zip: ../../50m_cultural/ne_50m_admin_0_sovereignty.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../50m_cultural/ne_50m_admin_0_sovereignty.shp $@ 1>/dev/null 2>&1

admin_0_sovereignty_110m.zip: ../../110m_cultural/ne_110m_admin_0_sovereignty.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../110m_cultural/ne_110m_admin_0_sovereignty.shp $@ 1>/dev/null 2>&1

admin_0_tiny_countries_50m.zip: ../../50m_cultural/ne_50m_admin_0_tiny_countries.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../50m_cultural/ne_50m_admin_0_tiny_countries.shp $@ 1>/dev/null 2>&1

admin_0_tiny_countries_110m.zip: ../../110m_cultural/ne_110m_admin_0_tiny_countries.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../110m_cultural/ne_110m_admin_0_tiny_countries.shp $@ 1>/dev/null 2>&1

admin_1_states_provinces_lakes_shp_10m.zip: ../../10m_cultural/ne_10m_admin_1_states_provinces_lakes_shp.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_cultural/ne_10m_admin_1_states_provinces_lakes_shp.shp $@ 1>/dev/null 2>&1

admin_1_states_provinces_lines_shp_10m.zip: ../../10m_cultural/ne_10m_admin_1_states_provinces_lines_shp.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_cultural/ne_10m_admin_1_states_provinces_lines_shp.shp $@ 1>/dev/null 2>&1

admin_1_states_provinces_lines_shp_50m.zip: ../../50m_cultural/ne_50m_admin_1_states_provinces_lines.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../50m_cultural/ne_50m_admin_1_states_provinces_lines.shp $@ 1>/dev/null 2>&1

admin_1_states_provinces_lines_shp_110m.zip: ../../110m_cultural/ne_110m_admin_1_states_provinces_lines.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../110m_cultural/ne_110m_admin_1_states_provinces_lines.shp $@ 1>/dev/null 2>&1

admin_1_states_provinces_shp_10m.zip: ../../10m_cultural/ne_10m_admin_1_states_provinces_shp.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_cultural/ne_10m_admin_1_states_provinces_shp.shp $@ 1>/dev/null 2>&1

admin_1_states_provinces_shp_50m.zip: ../../50m_cultural/ne_50m_admin_1_states_provinces_shp.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../50m_cultural/ne_50m_admin_1_states_provinces_shp.shp $@ 1>/dev/null 2>&1

admin_1_states_provinces_shp_110m.zip: ../../110m_cultural/ne_110m_admin_1_states_provinces_shp.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../110m_cultural/ne_110m_admin_1_states_provinces_shp.shp $@ 1>/dev/null 2>&1

antarctic_ice_shelves_lines_10m.zip: ../../10m_physical/ne_10m_antarctic_ice_shelves_lines.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_physical/ne_10m_antarctic_ice_shelves_lines.shp $@ 1>/dev/null 2>&1

antarctic_ice_shelves_lines_50m.zip: ../../50m_physical/ne_50m_antarctic_ice_shelves_lines.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../50m_physical/ne_50m_antarctic_ice_shelves_lines.shp $@ 1>/dev/null 2>&1

antarctic_ice_shelves_polys_10m.zip: ../../10m_physical/ne_10m_antarctic_ice_shelves_polys.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_physical/ne_10m_antarctic_ice_shelves_polys.shp $@ 1>/dev/null 2>&1

antarctic_ice_shelves_polys_50m.zip: ../../50m_physical/ne_50m_antarctic_ice_shelves_polys.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../50m_physical/ne_50m_antarctic_ice_shelves_polys.shp $@ 1>/dev/null 2>&1

bathymetry_A_10000_10m.zip: ../../10m_physical/ne_10m_bathymetry_all/ne_10m_bathymetry_A_10000.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_physical/ne_10m_bathymetry_all/ne_10m_bathymetry_A_10000.shp $@ 1>/dev/null 2>&1

bathymetry_B_9000_10m.zip: ../../10m_physical/ne_10m_bathymetry_all/ne_10m_bathymetry_B_9000.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_physical/ne_10m_bathymetry_all/ne_10m_bathymetry_B_9000.shp $@ 1>/dev/null 2>&1

bathymetry_C_8000_10m.zip: ../../10m_physical/ne_10m_bathymetry_all/ne_10m_bathymetry_C_8000.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_physical/ne_10m_bathymetry_all/ne_10m_bathymetry_C_8000.shp $@ 1>/dev/null 2>&1

bathymetry_D_7000_10m.zip: ../../10m_physical/ne_10m_bathymetry_all/ne_10m_bathymetry_D_7000.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_physical/ne_10m_bathymetry_all/ne_10m_bathymetry_D_7000.shp $@ 1>/dev/null 2>&1

bathymetry_E_6000_10m.zip: ../../10m_physical/ne_10m_bathymetry_all/ne_10m_bathymetry_E_6000.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_physical/ne_10m_bathymetry_all/ne_10m_bathymetry_E_6000.shp $@ 1>/dev/null 2>&1

bathymetry_F_5000_10m.zip: ../../10m_physical/ne_10m_bathymetry_all/ne_10m_bathymetry_F_5000.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_physical/ne_10m_bathymetry_all/ne_10m_bathymetry_F_5000.shp $@ 1>/dev/null 2>&1

bathymetry_G_4000_10m.zip: ../../10m_physical/ne_10m_bathymetry_all/ne_10m_bathymetry_G_4000.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_physical/ne_10m_bathymetry_all/ne_10m_bathymetry_G_4000.shp $@ 1>/dev/null 2>&1

bathymetry_H_3000_10m.zip: ../../10m_physical/ne_10m_bathymetry_all/ne_10m_bathymetry_H_3000.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_physical/ne_10m_bathymetry_all/ne_10m_bathymetry_H_3000.shp $@ 1>/dev/null 2>&1

bathymetry_I_2000_10m.zip: ../../10m_physical/ne_10m_bathymetry_all/ne_10m_bathymetry_I_2000.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_physical/ne_10m_bathymetry_all/ne_10m_bathymetry_I_2000.shp $@ 1>/dev/null 2>&1

bathymetry_J_1000_10m.zip: ../../10m_physical/ne_10m_bathymetry_all/ne_10m_bathymetry_J_1000.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_physical/ne_10m_bathymetry_all/ne_10m_bathymetry_J_1000.shp $@ 1>/dev/null 2>&1

bathymetry_K_200_10m.zip: ../../10m_physical/ne_10m_bathymetry_all/ne_10m_bathymetry_K_200.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_physical/ne_10m_bathymetry_all/ne_10m_bathymetry_K_200.shp $@ 1>/dev/null 2>&1

bathymetry_L_0_10m.zip: ../../10m_physical/ne_10m_bathymetry_all/ne_10m_bathymetry_L_0.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_physical/ne_10m_bathymetry_all/ne_10m_bathymetry_L_0.shp $@ 1>/dev/null 2>&1

coastline_10m.zip: ../../10m_physical/ne_10m_coastline.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_physical/ne_10m_coastline.shp $@ 1>/dev/null 2>&1

coastline_50m.zip: ../../50m_physical/ne_50m_coastline.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../50m_physical/ne_50m_coastline.shp $@ 1>/dev/null 2>&1

coastline_110m.zip: ../../110m_physical/ne_110m_coastline.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../110m_physical/ne_110m_coastline.shp $@ 1>/dev/null 2>&1

geographic_lines_10m.zip: ../../10m_physical/ne_10m_geographic_lines.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_physical/ne_10m_geographic_lines.shp $@ 1>/dev/null 2>&1

geographic_lines_50m.zip: ../../50m_physical/ne_50m_geographic_lines.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../50m_physical/ne_50m_geographic_lines.shp $@ 1>/dev/null 2>&1

geographic_lines_110m.zip: ../../110m_physical/ne_110m_geographic_lines.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../110m_physical/ne_110m_geographic_lines.shp $@ 1>/dev/null 2>&1

geography_marine_polys_10m.zip: ../../10m_physical/ne_10m_geography_marine_polys.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_physical/ne_10m_geography_marine_polys.shp $@ 1>/dev/null 2>&1

geography_marine_polys_50m.zip: ../../50m_physical/ne_50m_geography_marine_polys.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../50m_physical/ne_50m_geography_marine_polys.shp $@ 1>/dev/null 2>&1

geography_marine_polys_110m.zip: ../../110m_physical/ne_110m_geography_marine_polys.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../110m_physical/ne_110m_geography_marine_polys.shp $@ 1>/dev/null 2>&1

geography_regions_elevation_points_10m.zip: ../../10m_physical/ne_10m_geography_regions_elevation_points.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_physical/ne_10m_geography_regions_elevation_points.shp $@ 1>/dev/null 2>&1

geography_regions_elevation_points_50m.zip: ../../50m_physical/ne_50m_geography_regions_elevation_points.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../50m_physical/ne_50m_geography_regions_elevation_points.shp $@ 1>/dev/null 2>&1

geography_regions_elevation_points_110m.zip: ../../110m_physical/ne_110m_geography_regions_elevation_points.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../110m_physical/ne_110m_geography_regions_elevation_points.shp $@ 1>/dev/null 2>&1

geography_regions_points_10m.zip: ../../10m_physical/ne_10m_geography_regions_points.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_physical/ne_10m_geography_regions_points.shp $@ 1>/dev/null 2>&1

geography_regions_points_50m.zip: ../../50m_physical/ne_50m_geography_regions_points.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../50m_physical/ne_50m_geography_regions_points.shp $@ 1>/dev/null 2>&1

geography_regions_points_110m.zip: ../../110m_physical/ne_110m_geography_regions_points.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../110m_physical/ne_110m_geography_regions_points.shp $@ 1>/dev/null 2>&1

geography_regions_polys_10m.zip: ../../10m_physical/ne_10m_geography_regions_polys.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_physical/ne_10m_geography_regions_polys.shp $@ 1>/dev/null 2>&1

geography_regions_polys_50m.zip: ../../50m_physical/ne_50m_geography_regions_polys.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../50m_physical/ne_50m_geography_regions_polys.shp $@ 1>/dev/null 2>&1

geography_regions_polys_110m.zip: ../../110m_physical/ne_110m_geography_regions_polys.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../110m_physical/ne_110m_geography_regions_polys.shp $@ 1>/dev/null 2>&1

glaciated_areas_10m.zip: ../../10m_physical/ne_10m_glaciated_areas.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_physical/ne_10m_glaciated_areas.shp $@ 1>/dev/null 2>&1

glaciated_areas_50m.zip: ../../50m_physical/ne_50m_glaciated_areas.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../50m_physical/ne_50m_glaciated_areas.shp $@ 1>/dev/null 2>&1

glaciated_areas_110m.zip: ../../110m_physical/ne_110m_glaciated_areas.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../110m_physical/ne_110m_glaciated_areas.shp $@ 1>/dev/null 2>&1

graticules_1_10m.zip: ../../10m_physical/ne_10m_graticules_all/ne_10m_graticules_1.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_physical/ne_10m_graticules_all/ne_10m_graticules_1.shp $@ 1>/dev/null 2>&1

graticules_5_10m.zip: ../../10m_physical/ne_10m_graticules_all/ne_10m_graticules_5.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_physical/ne_10m_graticules_all/ne_10m_graticules_5.shp $@ 1>/dev/null 2>&1

graticules_10_10m.zip: ../../10m_physical/ne_10m_graticules_all/ne_10m_graticules_10.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_physical/ne_10m_graticules_all/ne_10m_graticules_10.shp $@ 1>/dev/null 2>&1

graticules_15_10m.zip: ../../10m_physical/ne_10m_graticules_all/ne_10m_graticules_15.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_physical/ne_10m_graticules_all/ne_10m_graticules_15.shp $@ 1>/dev/null 2>&1

graticules_20_10m.zip: ../../10m_physical/ne_10m_graticules_all/ne_10m_graticules_20.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_physical/ne_10m_graticules_all/ne_10m_graticules_20.shp $@ 1>/dev/null 2>&1

graticules_30_10m.zip: ../../10m_physical/ne_10m_graticules_all/ne_10m_graticules_30.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_physical/ne_10m_graticules_all/ne_10m_graticules_30.shp $@ 1>/dev/null 2>&1

graticules_1_50m.zip: ../../50m_physical/ne_50m_graticules_all/ne_50m_graticules_1.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../50m_physical/ne_50m_graticules_all/ne_50m_graticules_1.shp $@ 1>/dev/null 2>&1

graticules_5_50m.zip: ../../50m_physical/ne_50m_graticules_all/ne_50m_graticules_5.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../50m_physical/ne_50m_graticules_all/ne_50m_graticules_5.shp $@ 1>/dev/null 2>&1

graticules_10_50m.zip: ../../50m_physical/ne_50m_graticules_all/ne_50m_graticules_10.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../50m_physical/ne_50m_graticules_all/ne_50m_graticules_10.shp $@ 1>/dev/null 2>&1

graticules_15_50m.zip: ../../50m_physical/ne_50m_graticules_all/ne_50m_graticules_15.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../50m_physical/ne_50m_graticules_all/ne_50m_graticules_15.shp $@ 1>/dev/null 2>&1

graticules_20_50m.zip: ../../50m_physical/ne_50m_graticules_all/ne_50m_graticules_20.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../50m_physical/ne_50m_graticules_all/ne_50m_graticules_20.shp $@ 1>/dev/null 2>&1

graticules_30_50m.zip: ../../50m_physical/ne_50m_graticules_all/ne_50m_graticules_30.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../50m_physical/ne_50m_graticules_all/ne_50m_graticules_30.shp $@ 1>/dev/null 2>&1

graticules_1_110m.zip: ../../110m_physical/ne_110m_graticules_all/ne_110m_graticules_1.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../110m_physical/ne_110m_graticules_all/ne_110m_graticules_1.shp $@ 1>/dev/null 2>&1

graticules_5_110m.zip: ../../110m_physical/ne_110m_graticules_all/ne_110m_graticules_5.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../110m_physical/ne_110m_graticules_all/ne_110m_graticules_5.shp $@ 1>/dev/null 2>&1

graticules_10_110m.zip: ../../110m_physical/ne_110m_graticules_all/ne_110m_graticules_10.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../110m_physical/ne_110m_graticules_all/ne_110m_graticules_10.shp $@ 1>/dev/null 2>&1

graticules_15_110m.zip: ../../110m_physical/ne_110m_graticules_all/ne_110m_graticules_15.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../110m_physical/ne_110m_graticules_all/ne_110m_graticules_15.shp $@ 1>/dev/null 2>&1

graticules_20_110m.zip: ../../110m_physical/ne_110m_graticules_all/ne_110m_graticules_20.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../110m_physical/ne_110m_graticules_all/ne_110m_graticules_20.shp $@ 1>/dev/null 2>&1

graticules_30_110m.zip: ../../110m_physical/ne_110m_graticules_all/ne_110m_graticules_30.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../110m_physical/ne_110m_graticules_all/ne_110m_graticules_30.shp $@ 1>/dev/null 2>&1

wgs84_bounding_box_10m.zip: ../../10m_physical/ne_10m_graticules_all/ne_10m_wgs84_bounding_box.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_physical/ne_10m_graticules_all/ne_10m_wgs84_bounding_box.shp $@ 1>/dev/null 2>&1

wgs84_bounding_box_50m.zip: ../../50m_physical/ne_50m_graticules_all/ne_50m_wgs84_bounding_box.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../50m_physical/ne_50m_graticules_all/ne_50m_wgs84_bounding_box.shp $@ 1>/dev/null 2>&1

wgs84_bounding_box_110m.zip: ../../110m_physical/ne_110m_graticules_all/ne_110m_wgs84_bounding_box.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../110m_physical/ne_110m_graticules_all/ne_110m_wgs84_bounding_box.shp $@ 1>/dev/null 2>&1

lakes_10m.zip: ../../10m_physical/ne_10m_lakes.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_physical/ne_10m_lakes.shp $@ 1>/dev/null 2>&1

lakes_50m.zip: ../../50m_physical/ne_50m_lakes.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../50m_physical/ne_50m_lakes.shp $@ 1>/dev/null 2>&1

lakes_110m.zip: ../../110m_physical/ne_110m_lakes.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../110m_physical/ne_110m_lakes.shp $@ 1>/dev/null 2>&1

lakes_europe_10m.zip: ../../10m_physical/ne_10m_lakes_europe.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_physical/ne_10m_lakes_europe.shp $@ 1>/dev/null 2>&1

lakes_historic_10m.zip: ../../10m_physical/ne_10m_lakes_historic.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_physical/ne_10m_lakes_historic.shp $@ 1>/dev/null 2>&1

lakes_historic_50m.zip: ../../50m_physical/ne_50m_lakes_historic.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../50m_physical/ne_50m_lakes_historic.shp $@ 1>/dev/null 2>&1

lakes_north_america_10m.zip: ../../10m_physical/ne_10m_lakes_north_america.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_physical/ne_10m_lakes_north_america.shp $@ 1>/dev/null 2>&1

lakes_pluvial_10m.zip: ../../10m_physical/ne_10m_lakes_pluvial.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_physical/ne_10m_lakes_pluvial.shp $@ 1>/dev/null 2>&1

minor_islands_10m.zip: ../../10m_physical/ne_10m_minor_islands.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_physical/ne_10m_minor_islands.shp $@ 1>/dev/null 2>&1

minor_islands_coastline_10m.zip: ../../10m_physical/ne_10m_minor_islands_coastline.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_physical/ne_10m_minor_islands_coastline.shp $@ 1>/dev/null 2>&1

ocean_10m.zip: ../../10m_physical/ne_10m_ocean.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_physical/ne_10m_ocean.shp $@ 1>/dev/null 2>&1

ocean_50m.zip: ../../50m_physical/ne_50m_ocean.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../50m_physical/ne_50m_ocean.shp $@ 1>/dev/null 2>&1

ocean_110m.zip: ../../110m_physical/ne_110m_ocean.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../110m_physical/ne_110m_ocean.shp $@ 1>/dev/null 2>&1

us_parks_area_10m.zip: ../../10m_cultural/ne_10m_parks_and_protected_lands_area.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_cultural/ne_10m_parks_and_protected_lands_area.shp $@ 1>/dev/null 2>&1

us_parks_line_10m.zip: ../../10m_cultural/ne_10m_parks_and_protected_lands_line.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_cultural/ne_10m_parks_and_protected_lands_line.shp $@ 1>/dev/null 2>&1

us_parks_point_10m.zip: ../../10m_cultural/ne_10m_parks_and_protected_lands_point.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_cultural/ne_10m_parks_and_protected_lands_point.shp $@ 1>/dev/null 2>&1

physical_geographic_lines_110m.zip: ../../110m_physical/ne_110m_geographic_lines.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../110m_physical/ne_110m_geographic_lines.shp $@ 1>/dev/null 2>&1

playas_10m.zip: ../../10m_physical/ne_10m_playas.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_physical/ne_10m_playas.shp $@ 1>/dev/null 2>&1

playas_50m.zip: ../../50m_physical/ne_50m_playas.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../50m_physical/ne_50m_playas.shp $@ 1>/dev/null 2>&1

populated_places_10m.zip: ../../10m_cultural/ne_10m_populated_places.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_cultural/ne_10m_populated_places.shp $@ 1>/dev/null 2>&1

populated_places_50m.zip: ../../50m_cultural/ne_50m_populated_places.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../50m_cultural/ne_50m_populated_places.shp $@ 1>/dev/null 2>&1

populated_places_110m.zip: ../../110m_cultural/ne_110m_populated_places.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../110m_cultural/ne_110m_populated_places.shp $@ 1>/dev/null 2>&1

populated_places_simple_10m.zip: ../../10m_cultural/ne_10m_populated_places_simple.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_cultural/ne_10m_populated_places_simple.shp $@ 1>/dev/null 2>&1

populated_places_simple_50m.zip: ../../50m_cultural/ne_50m_populated_places_simple.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../50m_cultural/ne_50m_populated_places_simple.shp $@ 1>/dev/null 2>&1

populated_places_simple_110m.zip: ../../110m_cultural/ne_110m_populated_places_simple.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../110m_cultural/ne_110m_populated_places_simple.shp $@ 1>/dev/null 2>&1

railroads_10m.zip: ../../10m_cultural/ne_10m_railroads.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_cultural/ne_10m_railroads.shp $@ 1>/dev/null 2>&1

reefs_10m.zip: ../../10m_physical/ne_10m_reefs.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_physical/ne_10m_reefs.shp $@ 1>/dev/null 2>&1

rivers_europe_10m.zip: ../../10m_physical/ne_10m_rivers_europe.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_physical/ne_10m_rivers_europe.shp $@ 1>/dev/null 2>&1

rivers_lake_centerlines_10m.zip: ../../10m_physical/ne_10m_rivers_lake_centerlines.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_physical/ne_10m_rivers_lake_centerlines.shp $@ 1>/dev/null 2>&1

rivers_lake_centerlines_50m.zip: ../../50m_physical/ne_50m_rivers_lake_centerlines.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../50m_physical/ne_50m_rivers_lake_centerlines.shp $@ 1>/dev/null 2>&1

rivers_lake_centerlines_110m.zip: ../../110m_physical/ne_110m_rivers_lake_centerlines.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../110m_physical/ne_110m_rivers_lake_centerlines.shp $@ 1>/dev/null 2>&1

rivers_lake_centerlines_scale_ranks_10m.zip: ../../10m_physical/ne_10m_rivers_lake_centerlines_scale_rank.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_physical/ne_10m_rivers_lake_centerlines_scale_rank.shp $@ 1>/dev/null 2>&1

rivers_lake_centerlines_scale_ranks_50m.zip: ../../50m_physical/ne_50m_rivers_lake_centerlines_scale_rank.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../50m_physical/ne_50m_rivers_lake_centerlines_scale_rank.shp $@ 1>/dev/null 2>&1

rivers_north_america_10m.zip: ../../10m_physical/ne_10m_rivers_north_america.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_physical/ne_10m_rivers_north_america.shp $@ 1>/dev/null 2>&1

roads_10m.zip: ../../10m_cultural/ne_10m_roads.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_cultural/ne_10m_roads.shp $@ 1>/dev/null 2>&1

roads_north_america_10m.zip: ../../10m_cultural/ne_10m_roads_north_america.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_cultural/ne_10m_roads_north_america.shp $@ 1>/dev/null 2>&1

urban_areas_10m.zip: ../../10m_cultural/ne_10m_urban_areas.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_cultural/ne_10m_urban_areas.shp $@ 1>/dev/null 2>&1

urban_areas_50m.zip: ../../50m_cultural/ne_50m_urban_areas.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../50m_cultural/ne_50m_urban_areas.shp $@ 1>/dev/null 2>&1

urban_areas_landscan_10m.zip: ../../10m_cultural/ne_10m_urban_areas_landscan.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_cultural/ne_10m_urban_areas_landscan.shp $@ 1>/dev/null 2>&1

admin_0_antarctic_claims_10m.zip: ../../10m_cultural/ne_10m_admin_0_antarctic_claims.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_cultural/ne_10m_admin_0_antarctic_claims.shp $@ 1>/dev/null 2>&1

admin_0_antarctic_claim_limit_lines_10m.zip: ../../10m_cultural/ne_10m_admin_0_antarctic_claim_limit_lines.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_cultural/ne_10m_admin_0_antarctic_claim_limit_lines.shp $@ 1>/dev/null 2>&1

parks_and_protected_lands_scale_rank_10m.zip: ../../10m_cultural/ne_10m_parks_and_protected_lands_scale_rank.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_cultural/ne_10m_parks_and_protected_lands_scale_rank.shp $@ 1>/dev/null 2>&1

airports_10m.zip: ../../10m_cultural/ne_10m_airports.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_cultural/ne_10m_airports.shp $@ 1>/dev/null 2>&1

ports_10m.zip: ../../10m_cultural/ne_10m_ports.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_cultural/ne_10m_ports.shp $@ 1>/dev/null 2>&1

airports_50m.zip: ../../50m_cultural/ne_50m_airports.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../50m_cultural/ne_50m_airports.shp $@ 1>/dev/null 2>&1

ports_50m.zip: ../../50m_cultural/ne_50m_ports.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../50m_cultural/ne_50m_ports.shp $@ 1>/dev/null 2>&1

time_zones_10m.zip: ../../10m_cultural/ne_10m_time_zones.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_cultural/ne_10m_time_zones.shp $@ 1>/dev/null 2>&1

land_scale_ranks_10m.zip: ../../10m_physical/ne_10m_land_scale_rank.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_physical/ne_10m_land_scale_rank.shp $@ 1>/dev/null 2>&1

ocean_scale_ranks_10m.zip: ../../10m_physical/ne_10m_ocean_scale_rank.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_physical/ne_10m_ocean_scale_rank.shp $@ 1>/dev/null 2>&1

admin_0_tiny_countries_scale_rank_50m.zip: ../../50m_cultural/ne_50m_admin_0_tiny_countries_scale_rank.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../50m_cultural/ne_50m_admin_0_tiny_countries_scale_rank.shp $@ 1>/dev/null 2>&1

admin_1_states_provinces_shp_scale_rank_50m.zip: ../../50m_cultural/ne_50m_admin_1_states_provinces_shp_scale_rank.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../50m_cultural/ne_50m_admin_1_states_provinces_shp_scale_rank.shp $@ 1>/dev/null 2>&1

admin_1_states_provinces_lakes_shp_50m.zip: ../../50m_cultural/ne_50m_admin_1_states_provinces_lakes_shp.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../50m_cultural/ne_50m_admin_1_states_provinces_lakes_shp.shp $@ 1>/dev/null 2>&1

admin_1_states_provinces_shp_scale_rank_110m.zip: ../../110m_cultural/ne_110m_admin_1_states_provinces_shp_scale_rank.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../110m_cultural/ne_110m_admin_1_states_provinces_shp_scale_rank.shp $@ 1>/dev/null 2>&1

land_ocean_label_points_10m.zip: ../../10m_physical/ne_10m_land_ocean_label_points.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_physical/ne_10m_land_ocean_label_points.shp $@ 1>/dev/null 2>&1

minor_island_label_points_10m.zip: ../../10m_physical/ne_10m_minor_islands_label_points.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_physical/ne_10m_minor_islands_label_points.shp $@ 1>/dev/null 2>&1

admin_0_label_points_10m.zip: ../../10m_cultural/ne_10m_admin_0_label_points.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_cultural/ne_10m_admin_0_label_points.shp $@ 1>/dev/null 2>&1

land_ocean_seams_10m.zip: ../../10m_physical/ne_10m_land_ocean_seams.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_physical/ne_10m_land_ocean_seams.shp $@ 1>/dev/null 2>&1

admin_0_seams_10m.zip: ../../10m_cultural/ne_10m_admin_0_seams.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_cultural/ne_10m_admin_0_seams.shp $@ 1>/dev/null 2>&1

admin_1_seams_10m.zip: ../../10m_cultural/ne_10m_admin_1_seams.shp
	lockrun --lockfile=zip-it.lock --wait -- ./zip-it.sh ../../10m_cultural/ne_10m_admin_1_seams.shp $@ 1>/dev/null 2>&1



live: zips
	ls zips/*.zip | xargs -n1 -P4 python do-info.py
	s3cmd -c s3.cfg --acl-public --no-progress put zips/*.html zips/*.zip s3://cascadenik.teczno.com/data/ne-1.4/900913/

clean:
	rm -rf zips
	rm -f land_*m.zip admin_0_boundary_breakaway_disputed_areas_*m.zip admin_0_boundary_lines_land_*m.zip \
		  admin_0_boundary_lines_map_units_*m.zip admin_0_boundary_lines_maritime_indicator_*m.zip \
		  admin_0_boundary_map_units_*m.zip admin_0_breakaway_disputed_areas_*m.zip \
		  admin_0_breakaway_disputed_areas_scale_ranks_*m.zip admin_0_countries_*m.zip admin_0_map_subunits_*m.zip \
		  admin_0_map_units_*m.zip admin_0_pacific_groupings_*m.zip admin_0_scale_ranks_*m.zip \
		  admin_0_scale_ranks_with_minor_islands_*m.zip admin_0_sovereignty_*m.zip admin_0_tiny_countries_*m.zip \
		  admin_1_states_provinces_lakes_shp_*m.zip admin_1_states_provinces_lines_shp_*m.zip \
		  admin_1_states_provinces_shp_*m.zip antarctic_ice_shelves_lines_*m.zip antarctic_ice_shelves_polys_*m.zip \
		  bathymetry_A_10000_*m.zip bathymetry_B_9000_*m.zip bathymetry_C_8000_*m.zip bathymetry_D_7000_*m.zip \
		  bathymetry_E_6000_*m.zip bathymetry_F_5000_*m.zip bathymetry_G_4000_*m.zip bathymetry_H_3000_*m.zip \
		  bathymetry_I_2000_*m.zip bathymetry_J_1000_*m.zip bathymetry_K_200_*m.zip bathymetry_L_0_*m.zip \
		  coastline_*m.zip geographic_lines_*m.zip geography_marine_polys_*m.zip \
		  geography_regions_elevation_points_*m.zip geography_regions_points_*m.zip geography_regions_polys_*m.zip \
		  glaciated_areas_*m.zip graticules_1_*m.zip graticules_5_*m.zip graticules_10_*m.zip graticules_15_*m.zip \
		  graticules_20_*m.zip graticules_30_*m.zip wgs84_bounding_box_*m.zip lakes_*m.zip lakes_europe_*m.zip \
		  lakes_historic_*m.zip lakes_north_america_*m.zip lakes_pluvial_*m.zip minor_islands_*m.zip \
		  minor_islands_coastline_*m.zip ocean_*m.zip us_parks_area_*m.zip us_parks_line_*m.zip us_parks_point_*m.zip \
		  physical_geographic_lines_*m.zip playas_*m.zip populated_places_*m.zip populated_places_simple_*m.zip \
		  railroads_*m.zip reefs_*m.zip rivers_europe_*m.zip rivers_lake_centerlines_*m.zip \
		  rivers_lake_centerlines_scale_ranks_*m.zip rivers_north_america_*m.zip roads_*m.zip roads_north_america_*m.zip \
		  urban_areas_*m.zip urban_areas_landscan_*m.zip \
		  admin_0_antarctic_claims_*m.zip \
		  admin_0_antarctic_claim_limit_lines_*m.zip \
		  parks_and_protected_lands_scale_ranks_*m.zip \
		  airports_*m.zip \
		  ports_*m.zip \
		  time_zones_*m.zip \
		  land_scale_ranks_*m.zip \
		  ocean_scale_ranks_*m.zip \
		  admin_0_tiny_countries_scale_rank_*m.zip \
		  admin_1_states_provinces_shp_scale_rank_*m.zip \
		  land_ocean_label_points_*m.zip \
		  minor_island_label_points_*m.zip \
		  admin_0_label_points_*m.zip \
		  land_ocean_seams_*m.zip \
		  admin_0_seams_*m.zip \
		  admin_1_seams_*m.zip